# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=20)),
                ('goodsstock', models.CharField(max_length=20)),
                ('goodsinfo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='turnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousename', models.CharField(max_length=20, verbose_name='\u4ed3\u5e93\u540d')),
                ('warehouseinfo', models.CharField(max_length=50, verbose_name='\u4ed3\u5e93\u4fe1\u606f')),
                ('stock', models.CharField(max_length=20, verbose_name='\u5e93\u5b58')),
                ('inventory', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u79cd\u7c7b')),
            ],
        ),
    ]
