# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsinfo',
            field=models.CharField(max_length=50, verbose_name='\u7269\u54c1\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsname',
            field=models.CharField(max_length=20, verbose_name='\u7269\u54c1\u540d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsstock',
            field=models.CharField(max_length=20, verbose_name='\u5e93\u5b58'),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='quantity',
            field=models.CharField(max_length=20, verbose_name='\u6570\u91cf'),
        ),
    ]
